run:
	python tembusu1_paper_edge.py
	python tembusu2_paper_normal.py
	python tembusu5_vgg_edge.py
	python tembusu6_vgg_normal.py
	python tembusu3_caffenet_edge.py
	python tembusu4_caffenet_normal.py

runOther:
	python tembusu9_inceptionresnet_edge.py
	python tembusu10_inceptionresnet_normal.py
	python tembusu7_resnext_edge.py
	python tembusu8_resnext_normal.py
