submitAll:
	dos2unix *.pbs
	qsub submit1_caffenet_edge.pbs
	qsub submit2_caffenet_normal.pbs
	qsub submit3_vgg_edge.pbs
	qsub submit4_vgg_normal.pbs
	qsub submit5_paper_edge.pbs
	qsub submit6_paper_normal.pbs
	qsub submit7_inception_edge.pbs
	qsub submit8_inception_normal.pbs
