run:
	python tembusu5_paper_edge_good_dropout_0_0.py 
	python tembusu6_paper_edge_good_dropout_0_4.py 
	python tembusu7_paper_edge_good_512.py 
	python tembusu8_paper_edge_good_2048.py 
	python tembusu9_paper_edge_good_standard.py 
